name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
        version: ${{ steps.semantic.outputs.version }}

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Tag version
          id: semantic
          uses: paulhatch/semantic-version@v5.4.0
          with:
            tag_prefix: ""
            change_path: "src/ templates/"
            enable_prerelease_mode: true


  build:
    needs:
      - version
    runs-on: ubuntu-latest
    env:
      PUNCH_VERSION: ${{ needs.version.outputs.version }}

    strategy:
      matrix:
        env: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-apple-darwin, aarch64-apple-darwin]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.46.3

      - name: Build and zip binary for ${{ matrix.env }}
        run: ./scripts/ci_release.sh ${{ matrix.env }}

      - name: Create Release Asset for ${{ matrix.env }}
        id: create_release_asset
        uses: ncipollo/release-action@v1.14.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          allowUpdates: true
          tag: ${{ needs.version.outputs.version }}
          artifacts: "./bin/*"
